#!/bin/bash

echo $XDG_CURRENT_DESKTOP
echo $DESKTOP_SESSION
echo $XDG_SESSION_TYPE

DESKTOP="$XDG_CURRENT_DESKTOP"

UBUNTU_PART="${DESKTOP%%:*}"
GNOME_PART="${DESKTOP##*:}"

echo "DESKTOP_SESSION Part: $UBUNTU_PART"
echo "CURRENT_DESKTOP Part: $GNOME_PART"
